const concat = require('gulp-concat');
const del = require('del');
const gulp = require('gulp');
const webpack = require('webpack');
const gulpWebpack = require('webpack-stream');

// Remove base64 font.css files generated by webpack
gulp.task('clean:fonts', function () {
  return del([
    'dist/eot.css',
    'dist/ttf.css',
    'dist/woff.css',
    'dist/woff2.css'
  ]);
});

// Build our webpack 4 bundles
gulp.task('build:webpack', function(cb) {
    return gulp.src('src/index.js')
    .pipe(gulpWebpack(require('./webpack.config.js')), webpack)
    .pipe(gulp.dest('dist/'));
});

// Concat minified base64 font CSS files with main CSS file
// **POST WEBPACK BUNDLE**
gulp.task('build:css', function() {
    return gulp.src(
        [
            './dist/eot.css',
            './dist/ttf.css',
            './dist/woff.css',
            './dist/woff2.css',
            './dist/css/app.min.css'
        ]
    )
    .pipe(concat('app.min.css'))
    .pipe(gulp.dest('./dist/css'));
  });

  gulp.task('default', gulp.series('build:webpack', 'build:css', 'clean:fonts'));